miniBUDE Timer and Tuning Updates
hpcgroup/miniBUDE pull request #5
Opened 2024-02-02 01:56 UTC by pranav-sivaraman

- [ ] Double check data movement
- [ ] Add configurable warmup iterations
- [ ] Add configurable block size to all models.

2024-02-08 14:33 UTC, jhdavis8 requested changes
Looks good, two small changes to discuss

2024-02-08 14:33 UTC, jhdavis8 commented on src/acc/fasten.hpp
> -    std::free(energies);
`energies` is calloc'd above so I believe we need to free it before the name goes out of scope.

2024-02-08 14:33 UTC, jhdavis8 commented on src/omp/fasten.hpp
> -    std::free(energies);
Same here for energies, I think it still needs to be freed like for OpenACC

2024-02-08 15:43 UTC, jhdavis8 commented on src/acc/fasten.hpp
> -    std::free(energies);
Or change energies to point to sample.energies

2024-02-08 20:28 UTC, jhdavis8 approved these changes

2024-02-12 18:54 UTC, jhdavis8 commented
@joy-kitson would you be able to review this one as well?

2024-02-12 19:04 UTC, joy-kitson reviewed
It looks like in most of the models you're timing allocation under the umbrella of host to device data movement, unless I'm missing something. I think it might be worth discussing whether or not this is the intended behavior for our timers, as if it is I think I need to make some changes in Cloverleaf (and if memory serves, we may need to do so in some of the other apps as well).

2024-02-12 19:04 UTC, joy-kitson commented on src/acc/fasten.hpp
> +  sample.deviceToHost = {deviceToHostStart, deviceToHostEnd};
Is there a reason we're saving the start and end times rather than just the time elapsed?

2024-02-12 19:04 UTC, joy-kitson commented on src/bude.h
> +  std::optional<std::pair<TimePoint, TimePoint>> deviceToHost;
I guess it makes sense to do it this way if that's what's in the existing code, but it does still seem rather unorthodox, and also doesn't quite line up with what we do in the other codes

2024-02-12 19:04 UTC, joy-kitson commented on src/cuda/fasten.hpp
> +    auto hostToDeviceStart = now();
Does the `allocate` function preform a copy for the passed buffer? If not, I thought we weren't planning on timing memory allocations, just data movement?

2024-02-12 19:04 UTC, joy-kitson commented on src/cuda/fasten.hpp
> +    auto hostToDeviceStart = now();
Took a look at it and it seems to just allocate, so not sure if you intend to time those (if you do I probably need to adjust some timers in Cloverleaf)

2024-02-12 21:54 UTC, pranav-sivaraman commented on src/bude.h
> +  std::optional<std::pair<TimePoint, TimePoint>> deviceToHost;
The final output is just the elapsed time so I think it shouldn't be a problem copying the way they do it.

2024-02-12 21:58 UTC, pranav-sivaraman commented on src/acc/fasten.hpp
> +  sample.deviceToHost = {deviceToHostStart, deviceToHostEnd};
See below

2024-02-12 21:59 UTC, pranav-sivaraman commented on src/cuda/fasten.hpp
> +    auto hostToDeviceStart = now();
`allocate` is an overloaded function where the argument is a `std::vector` which then calls `allocate` again where the argument is just a size for the allocation. 

But we decided in the meeting that we are including the allocation time and copy so this is a non-issue tho I need to ensure that is consistent

2024-02-16 18:16 UTC, merged